a = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('É alfanumeriso? ', a.isalnum())
print('Está em maisculos? ', a.isupper())
print(' Está em minuscilas? ', a.islower())
print('Está Capitalizada? ', a.istitle())
