n = str(input('Digite seu nome completo:')).strip()
nome = n.split()
print('Olá {} é um prazer te conhecer'.format(nome))
print('Seu primeiro nome é {}'.format(nome[0]))
print('O seu útimo nome é {}'.format(nome[len(nome)-1]))
